spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/santander_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    open-in-view: false
    hibernate:
      ddl-auto: validate
